# 华为笔试 无尽的任务

## 题目1：无尽的任务

小杰在工作中有很多任务，为了保持高效，小杰在同一时间内只处理一项任务。在当前交付周期里，有n个任务（1<=n<=1000）,每个任务的价值为vi(1<=vi<=1000)，需要完成的时间为（1<=ti<10000）,最后期限为di(1<=di<=1000),超过最后期限完成则产生不了任何价值，球，求小杰能输出的最大价值是多少。
**解答要求**：
时间限制：C/C++ 1000ms,其他语言：2000ms
内存限制：C/C++ 256MB,其他语言：512MB

### 样例 1

#### 输入

```bash
3
3 3 10
1 1 10
10 10 10
```
#### 输出

```bash
10
```
#### 解释：

前两个任务价值和才6，第三个是10，如果选择前两个任务的任何一个，那就完成不了第三个任务。所以只要选择第三个任务去完成，就可以获取最大的任务价值。

### 样例2

#### 输入

```bash
3
6 5 4
5 1 5
5 5 10
```

#### 输出

```bash
10
```

#### 解释

结果是选择第一个和第三个任务。选择第一个任务花了5个单位的时间，第二个任务需要在期限5以前完成，所以选择不了，只能再选择第三个任务。

## 穷举方法

我首先写一个穷举的方法，这可以作为接下来一些算法的验证程序。

In [35]:
import numpy as np
num=5
value=np.random.randint(0,10,num)
time_take=np.random.randint(1,5,num)
time_dead=np.random.randint(5,10,num)
print(value)
print(time_take)
print(time_dead)

[8 8 9 9 3]
[4 1 4 1 2]
[5 5 7 6 7]


In [36]:
steps_value=np.ones((num,2**(num-1)))*np.inf
steps_time=np.ones((num,2**(num-1)))*np.inf
choice=[False,True]
for l in range(num):
        if l==0:
            steps_time[l,0]=time_take[0]*0
            steps_value[l,0]=value[0]*0
            steps_time[l,1]=time_take[0]
            steps_value[l,1]=value[0]
        else:
            steps_value[l,0:2**(l-1)]=steps_value[l-1,0:2**(l-1)]
            steps_value[l,2**(l-1):2**l]=steps_value[l-1,0:2**(l-1)]+value[l]
            steps_time[l,0:2**(l-1)]=steps_time[l-1,0:2**(l-1)]
            steps_time[l,2**(l-1):2**l]=steps_time[l-1,0:2**(l-1)]+time_take[l]
            steps_value[l,steps_time[l,:]>time_dead[l]]=np.inf
            steps_time[l,steps_time[l,:]>time_dead[l]]=np.inf
print(steps_time[-1,:])
print(steps_value[-1,:])

[ 0.  1.  4.  5.  1.  2.  5.  6.  2.  3.  6.  7.  3.  4.  7. inf]
[ 0.  8.  9. 17.  9. 17. 18. 26.  3. 11. 12. 20. 12. 20. 21. inf]
